#!/usr/bin/env python3

# Takes in a string of text representing a genome,
# integers representing k-mer length, clump window
# size and how many times the k-mer must occur.
# Returns all k-mers that satisfied theese conditions.


# Problem URL: https://rosalind.info/problems/ba1e/

import argparse
from rosalind_utils import read_input


def find(text, kmer_length, window, kmer_count):
    print(f"got {text}, {kmer_length}, {window}, {kmer_count}")
    pass


def main():
    parser = argparse.ArgumentParser(
             description="Return all distinct k-mers forming clumps")

    parser.add_argument("text", help="Full text string or file")
    parser.add_argument("kmer_length", help="How long the k-mers should be")
    parser.add_argument("window_size", help="How big the window should be")
    parser.add_argument("kmer_count", help="How many kmers for a clump")

    args = parser.parse_args()

    text = read_input(args.text)
    kmer_length = read_input(args.text)
    window = read_input(args.window_size)
    kmer_count = read_input(args.kmer_count)

    result = find(text, kmer_length, window, kmer_count)
    # print(" ".join(map(str, result)))


if __name__ == "__main__":
    main()
